sudo: required

language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "awt-05"
    token: ${SONAR_TOKEN}

script:
  - ./gradlew check
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
